parameters:
  twig.paths:
    - "%template_dir%/views"
    - "%template_dir%/src/views"
  twig.options:
    debug:            "%WP_DEBUG%"
    charset:          "utf-8"
    cache:            false
    auto_reload:      "%WP_DEBUG%"
    strict_variables: "%WP_DEBUG%"
    autoescape:       false
    optimizations:    -1
  logger.name: "SuperTheme"
  logger.path: "%template_dir%/var/logs.log"
  logger.level: "WARNING"
  wordpress.theme_support:
    - "html5"
    - "post-thumbnails"
    - "custom-logo"
  wordpress.translations: "%template_dir%/languages"
  wordpress.image_sizes:
    fullscreen: [1920, 1080, true]
  wordpress.menus:
    primary_menu: "Primary Menu"
    footer_menu: "Footer Menu"
  wordpress.sidebars:
    - { id: "left_sidebar", name: "Left Sidebar", description: "Left Sidebar" }
    - { id: "right_sidebar", name: "Right Sidebar", description: "Right Sidebar" }
  wordpress.styles:
    - { id: "slick", source: "%template_uri%/web/libs/slick-carousel/slick/slick.css", deps: ~ }
    - { id: "slick_theme", source: "%template_uri%/web/libs/slick-carousel/slick/slick-theme.css", deps: ["slick"] }
    - { id: "app", source: "%template_uri%/web/stylesheets/app.css", deps: ["slick_theme"] }
  wordpress.scripts:
    - { id: "app", source: "%template_uri%/web/scripts-min/app.min.js", deps: ["jquery"], header: false }

services:
  # just the basics
  http:
    class: "Symfony\\Component\\Form\\Extension\\HttpFoundation\\HttpFoundationExtension"
  session:
    class: "Symfony\\Component\\HttpFoundation\\Session\\Session"
    arguments: ["@session.bridge"]
  session.bridge:
    class: "Symfony\\Component\\HttpFoundation\\Session\\Storage\\PhpBridgeSessionStorage"
  translater:
    class: "Symfony\\Component\\Translation\\Translator"
    arguments: ["en"]
  # keep track of every detail
  logger:
    class: "Monolog\\Logger"
    arguments: ["%logger.name%"]
    calls:
      - ["pushHandler", ["@logger.stream"]]
  logger.stream:
    class: "Monolog\\Handler\\StreamHandler"
    arguments: ["%logger.path%", "%logger.level%"]
  # get twiggy with it
  twig.loader:
    class: "Twig_Loader_Filesystem"
    arguments: ["%twig.paths%"]
  twig.debug:
    class: "Twig_Extension_Debug"
  twig.acf:
    class: "Supertheme\\WordPress\\Twig\\ACF"
  twig.wordpress:
    class: "Supertheme\\WordPress\\Twig\\WordPress"
  twig.supertheme:
    class: "Supertheme\\WordPress\\Twig\\SuperTheme"
    arguments: ["@twig.acf", "@twig.wordpress"]
  twig.environment:
    class: "Twig_Environment"
    arguments: ["@twig.loader", "%twig.options%"]
    calls:
      - ["addExtension", ["@twig.debug"]]
      - ["addGlobal", ["SP", "@twig.supertheme"]]
